### ISSUE TITLE
Windows Defender reports malware in package

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/aws-vault-chocolatey#31]
Several people are reporting issues with the latest version of the package.

> Recent versions of the aws-vault package appear to contain multiple viruses and malware. Windows reports it as containing "Trojan:Win32/Wacatac.B!ml" for at least the last 2 versions and immediately quarantines it.

> I've installed the choco package aws-vault (5.4.2) and Windows Defender reported the malware "Trojan:Win32/Wacatac.B!ml" malware inside the nupkg file.
Can you verify this?

Related: https://github.com/99designs/aws-vault/issues/566

**Comment by gusztavvargadr** [comment]
I've double checked back until version 5.3.2 and the binaries included in the Chocolatey package match the hashes from https://github.com/99designs/aws-vault/releases/. This indeed seems to be a false positive.

**Comment by magnopus-swifty** [comment]
Confirmed that Windows will quarantine the executables on my current version of Windows:

OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362

Windows Defender Antivirus
Last update: 5/6/2020

Trojan:Win32/Wacatac.B!ml

**Comment by Stefan-Hanke** [comment]
Confirmed for Win10 1903, OS Build 18362.778
Windows Defender "Security Intelligence Version" 1.315.160.0, Last update 07/05/2020, 5:50 UTC+1

**Comment by gusztavvargadr** [comment]
@magnopus-swifty @Stefan-Hanke thanks for the details and thanks again for reporting the issue.

I've tried scanning myself recent versions with the following configuration:

Microsoft Windows [Version 10.0.18363.815]
Security Intelligence Version 1.315.213.0

It reports the issue you mention with 5.4.2 but not with 5.4.1.

I've also published the latest two pending versions, which are not reported by Windows Defender either. They are still pending review on Chocolatey but you can give them a go:

https://chocolatey.org/packages/aws-vault/5.4.3
https://chocolatey.org/packages/aws-vault/5.4.4

So to me it still seems to be a false positive, please let me know if you can try the latest versions.

**Comment by Stefan-Hanke** [comment]
I've 
- downloaded both versions directly and ran a Custom Scan over both files - no threats detected.
- installed aws-vault 5.4.4 - installation as expected.
- ran a Custom Scan over `C:\ProgramData\chocolatey\bin` - no threats detected.

Windows Defender "Security Intelligence Version" 1.315.189.0, Last update 07/05/2020, 18:26 UTC+1

I'll run a full scan now.

**Comment by gusztavvargadr** [comment]
@Stefan-Hanke thanks for the confirmation, glad to hear it works with the latest.

**Comment by magnopus-swifty** [comment]
Confirmed, works with latest for me as well.

**Comment by midasf** [comment]
Today i had the same issue, different trojan, :Win32/Fuerboos.A!cl, validated the hash 0C93108F1CF1B920A84808E664245D272A2179FC931485D3C6F6989C350E6EFA.
aws-vault 5.4.4
Security Intelligence Version 1.315.896.0
Ran scan afterwards, nothing detected.

**Comment by gusztavvargadr** [comment]
@midasf thanks for reporting this, I still have the same trojan reported with 1.315.1036.0.

I've reopened this, in the meantime you can try the previous patch version that now does not seem to trigger any alters https://chocolatey.org/packages/aws-vault/5.4.3.

**Comment by gusztavvargadr** [comment]
@midasf sorry for the delay, are you still experiencing this? To me with the latest defintion updates at `1.317.113.0` it is no longer being reported, was probably a false positive again.

**Comment by mentos1386** [comment]
@gusztavvargadr I'm having the same issue on fresh windows install with `1.137.390.0` version of security intelegences.

**Comment by gusztavvargadr** [comment]
With the latest updates as of now `1.317.604.0`, the latest version `5.4.4` seems to be fine, but earlier ones report issues:

For `5.4.2` I get `Trojan:Win32/Wacatac.B!ml` and for `5.4.3` it's `Trojan:Win32/Fuerboos.A!cl`.

Can someone please double check and confirm that the latest `5.4.4` is working now.

FYI, since this repo is only about packaging the tool, I raised this at the original authors at https://github.com/99designs/aws-vault/issues/599.

**Comment by thrixton** [comment]
I get the same result with 5.4.4 :(
When I download direct from 99D github, Win Defender quarantines it as well.
I've added more to the 99Designs issue [here](https://github.com/99designs/aws-vault/issues/566)
4.7.3 is working (via choco) it appears.

**Comment by thrixton** [comment]
This should be fixed with the latest WinDef definitions

**Comment by gusztavvargadr** [comment]
@thrixton thanks heaps for the help with this over at https://github.com/99designs/aws-vault/issues/566#issuecomment-639268939.

@magnopus-swifty @Stefan-Hanke @midasf @mentos1386 thank you all for the detailed debugging information.

I'm closing this now but feel free to reopen in case any of you notices the issue again.
